### ISSUE TITLE
Fails if file naming convention includes a dot . in the name itself

### ISSUE THREAD

**Issue by YarivGilad** [kristoferbaxter/typescript-esm#12]
**Before:** index.js
import Alian from "./space/ships.manager";
// ...

**After:** index.mjs
import Alian from "./space/ships.mjs";
//...

**Expected:** index.mjs
import Alian from "./space/ships.manager.mjs";
//...

**Comment by kristoferbaxter** [comment]
Whoops! Good bug.

Taking a look.
